//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Management_System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Real_Estate_Management_System.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_BILLING_BILL_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("REMS_BILLING_BILL_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_BILLING_ELECTRICITY {
            get {
                object obj = ResourceManager.GetObject("REMS_BILLING_ELECTRICITY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_BILLING_EXPORT_TO_PDF {
            get {
                object obj = ResourceManager.GetObject("REMS_BILLING_EXPORT_TO_PDF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_BILLING_INTERNET {
            get {
                object obj = ResourceManager.GetObject("REMS_BILLING_INTERNET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_BILLING_RENTAL {
            get {
                object obj = ResourceManager.GetObject("REMS_BILLING_RENTAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_BILLING_SAVE_BILL {
            get {
                object obj = ResourceManager.GetObject("REMS_BILLING_SAVE_BILL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_BILLING_WATER {
            get {
                object obj = ResourceManager.GetObject("REMS_BILLING_WATER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_DASHBOARD_BILLS_ISSUED {
            get {
                object obj = ResourceManager.GetObject("REMS_DASHBOARD_BILLS_ISSUED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_DASHBOARD_CASH_ON_HAND {
            get {
                object obj = ResourceManager.GetObject("REMS_DASHBOARD_CASH-ON-HAND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_DASHBOARD_EXPENSES {
            get {
                object obj = ResourceManager.GetObject("REMS_DASHBOARD_EXPENSES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_DASHBOARD_OVERDUES {
            get {
                object obj = ResourceManager.GetObject("REMS_DASHBOARD_OVERDUES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_DASHBOARD_PAID_BILLS {
            get {
                object obj = ResourceManager.GetObject("REMS_DASHBOARD_PAID_BILLS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_DASHBOARD_RECEIVABLES {
            get {
                object obj = ResourceManager.GetObject("REMS_DASHBOARD_RECEIVABLES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_DASHBOARD_RECEIVED {
            get {
                object obj = ResourceManager.GetObject("REMS_DASHBOARD_RECEIVED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_DASHBOARD_TENANTS {
            get {
                object obj = ResourceManager.GetObject("REMS_DASHBOARD_TENANTS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_DASHBOARD_UNPAIDS {
            get {
                object obj = ResourceManager.GetObject("REMS_DASHBOARD_UNPAIDS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_INTERNET_LIGHT {
            get {
                object obj = ResourceManager.GetObject("REMS_INTERNET_LIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_INVOICE {
            get {
                object obj = ResourceManager.GetObject("REMS_INVOICE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_INVOICE_LIGHT {
            get {
                object obj = ResourceManager.GetObject("REMS_INVOICE-LIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_INVOICE_LIGHT1 {
            get {
                object obj = ResourceManager.GetObject("REMS_INVOICE-LIGHT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_LOGIN {
            get {
                object obj = ResourceManager.GetObject("REMS_LOGIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_LOGIN_BUTTON {
            get {
                object obj = ResourceManager.GetObject("REMS_LOGIN_BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_LOGIN_PASSWORD {
            get {
                object obj = ResourceManager.GetObject("REMS_LOGIN_PASSWORD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_LOGO___DARK {
            get {
                object obj = ResourceManager.GetObject("REMS LOGO - DARK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_LOGO___DARK_TRANSLUCENT {
            get {
                object obj = ResourceManager.GetObject("REMS LOGO - DARK_TRANSLUCENT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_LOGO___LIGHT {
            get {
                object obj = ResourceManager.GetObject("REMS LOGO - LIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_LOGOUT_LIGHT {
            get {
                object obj = ResourceManager.GetObject("REMS_LOGOUT_LIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_OVERDUE {
            get {
                object obj = ResourceManager.GetObject("REMS_OVERDUE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_PAYMENTS_LIGHT {
            get {
                object obj = ResourceManager.GetObject("REMS_PAYMENTS_LIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_PAYMENTS_LIGHT1 {
            get {
                object obj = ResourceManager.GetObject("REMS_PAYMENTS_LIGHT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_REPORTS_LIGHT {
            get {
                object obj = ResourceManager.GetObject("REMS_REPORTS_LIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_RESET_ICON {
            get {
                object obj = ResourceManager.GetObject("REMS_RESET_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_ROOMS_LIGHT {
            get {
                object obj = ResourceManager.GetObject("REMS_ROOMS_LIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_SETTINGS_LIGHT {
            get {
                object obj = ResourceManager.GetObject("REMS_SETTINGS_LIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_TENANTS_LIGHT {
            get {
                object obj = ResourceManager.GetObject("REMS_TENANTS_LIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_TENANTS_LIST_BG {
            get {
                object obj = ResourceManager.GetObject("REMS_TENANTS_LIST_BG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_TENANTS_LIST_BG1 {
            get {
                object obj = ResourceManager.GetObject("REMS_TENANTS_LIST_BG1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_THEMED_GOTO {
            get {
                object obj = ResourceManager.GetObject("REMS_THEMED_GOTO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_USER {
            get {
                object obj = ResourceManager.GetObject("REMS_USER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_USER_DARK {
            get {
                object obj = ResourceManager.GetObject("REMS_USER_DARK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REMS_UTILITIES_LIGHT {
            get {
                object obj = ResourceManager.GetObject("REMS_UTILITIES_LIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
